### ISSUE TITLE
It verifies the wong username and password

### ISSUE THREAD

**Issue by T-Dynamos** [tanveebajaj36/Password-Authentication#1]
```
Enter Your Username : AnshDadwal
Enter Your Password :
Verified

[Program finished]
```

**Comment by tanveebajaj36** [comment]
Thank you for your review. I'm on it 👍

Sent from Yahoo Mail on Android 
 
  On Thu, Jun 3, 2021 at 13:11, ***@***.***> wrote:   

Enter Your Username : AnshDadwal
Enter Your Password :
Verified

[Program finished]

**Comment by tanveebajaj36** [comment]
Hi, thanks for your feedback. Repository updated kindly check again.

**Comment by T-Dynamos** [comment]
import getpass to hide password written

**Comment by tanveebajaj36** [comment]
Getpass function is not working in pycharm or VS code. You can share with me if you have tried it.

**Comment by T-Dynamos** [comment]
write this in command line  "pip install getpass'

**Comment by tanveebajaj36** [comment]
That didn't work in PyCharm, I tried something else but the code did ran at the end, correctly. I updated it in repo.

**Comment by tanveebajaj36** [comment]
Updated.

**Comment by T-Dynamos** [comment]
See this And Update
import getpass
h1 = '================================'
def register():
    username = input("Please input your desired username =  ")
    password = getpass.getpass("Please input your desired password =  ")
    file = open("accountfile.txt","a")
    file.write(username)
    file.write(" ")
    file.write(password)
    file.write("\n")
    file.close()
    print(" Registration Successful !")
def login():
    username = input("Please enter your username = ")
    password = getpass.getpass("Please enter your password = ")
    for line in open("accountfile.txt","r").readlines():
        login_info = line.split()
        if username == login_info[0] and password == login_info[1]:
            print("Correct credentials!")
            return True
            exit()
    print("Incorrect credentials.")
    exit()
    print("Try Again")
    return login()
print(h1)
print("Do you want to Login or Register")
print(h1)
a = input("[(login (l) /register (r)] ==> ")
if a == 'login':
login()
if a == 'register':
register()
if a == 'l':
login()
if a == 'r':
register()
else:
exit()

Or download file =
